[package]
name = "chipioindustries/influx-demo"
description = "An experiment with InfluxDB."
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Llama = "chipioindustries/llama@1.2.2"
Maid = "chipioindustries/maid@1.0.1"
Promise = "evaera/promise@4.0.0"
Roact = "roblox/roact@1.4.2"
RoactHooks = "kampfkarren/roact-hooks@0.4.1"
RoactRodux = "chipioindustries/roact-rodux@1.0.4"
Remotes = "chipioindustries/remotes@1.0.1"
ReplicationMiddleware = "chipioindustries/replication-middleware@1.0.0"
Rodux = "chipioindustries/rodux@3.0.4"
RoduxHooks = "solarhorizon/rodux-hooks@0.3.0"
Signal = "chipioindustries/signal@1.1.1"
t = "osyrisrblx/t@3.0.0"
Timer = "sleitnick/timer@1.1.1"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"